name: docs
on: [push]
jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Cache Nix store
        uses: actions/cache@v2
        with:
          path: ~/.cache/nix
          key: ${{ runner.os }}-nix-${{ hashFiles('**/flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Build with Flake.nix
        run: |
          nix develop
          nix develop --command rustc --version
          nix develop --command rustc --print sysroot

      - name: Donwload kernel
        run: |
            LD_LIBRARY_PATH='' nix develop --command ./script.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: Documentation/output
